### PR TITLE
finally got appengine-magic working with lein 2

### PR DESCRIPTION
**Pull request by nukemberg**
removed dev dependencies from WEB-INF/lib; appengine-prepare is working.

### CODE REVIEW

**Comment by gcv** [comment]
This looks good! I'm away from my machine for the next week, but I'll merge this change in as soon as I return.

**Comment by gcv** [comment]
I like your patch, but while testing it, I discovered that it has an implicit dependency on JDK 7. me.raynes.fs uses java.nio.file.Files, which does not exist on JDK 6. I myself write Clojure using the basic JDK 6 included with OS X, and am uncomfortable making my libraries incompatible with such a widely installed JDK. Any chance you could replace the dependency with something like Apache Commons IO, which I think provides similar functionality to me.raynes.fs and is already an appengine-magic dependency?

**Comment by nukemberg** [comment]
Sure, i'll rewrite.

**Comment by nukemberg** [comment]
It seems that me.raynes.fs does not require jdk 7. i looks like the code will test for jdk 7 features at compile time and should work just fine with jdk 6 - look [here](https://github.com/Raynes/fs/blob/master/src/me/raynes/fs.clj#L142). If you are still unhappy with raynes.fs, i'll rewrite with apache commons-io as requested.

**Comment by gcv** [comment]
Hey, sorry about the delayed response... I see what you mean, but when I use your patch and then run `lein appengine-clean` inside a project, I get this:

```
java.lang.ClassNotFoundException: java.nio.file.Files
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:61)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:171)
    at me.raynes.fs$eval19$loading__4910__auto____20.invoke(fs.clj:1)
    at me.raynes.fs$eval19.invoke(fs.clj:1)
```

`java.nio.file.Files` is a JDK 7 feature.

**Comment by nukemberg** [comment]
you are correct. Apparently (try (import )) is not available in 1.4.4, upgraded to 1.4.5 which does contains this.

**Comment by roti** [comment]
So, any chances these changes will be accepted in the near future?

**Comment by gcv** [comment]
Thanks, and apologies again for the delay. Since I upgraded to Mavericks, I don't have a Java 6 SDK anymore, so I couldn't really test if that last change worked, but I guess that matters much less now.

**Pull request merged**
